### ISSUE TITLE
error on startup

### ISSUE THREAD

**Issue by iggnaT** [carykh/yoyleCityWords#9]
i know this project is like 9 years old but here is the error it gives me
`java.lang.NoSuchMethodError: 'void processing.core.PVector.add(processing.core.PVector)'`
full error:
`RuntimeException: java.lang.NoSuchMethodError: 'void processing.core.PVector.add(processing.core.PVector)'
java.lang.RuntimeException: java.lang.NoSuchMethodError: 'void processing.core.PVector.add(processing.core.PVector)'
	at processing.opengl.PSurfaceJOGL.lambda$initAnimator$2(PSurfaceJOGL.java:413)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NoSuchMethodError: 'void processing.core.PVector.add(processing.core.PVector)'
	at saito.objloader.BoundingBox.<init>(BoundingBox.java:46)
	at saito.objloader.OBJModel.translateToCenter(OBJModel.java:659)
	at yoyleCityWords.setup(yoyleCityWords.java:198)
	at processing.core.PApplet.handleDraw(PApplet.java:2142)
	at processing.opengl.PSurfaceJOGL$DrawListener.display(PSurfaceJOGL.java:822)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:692)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:674)
	at jogamp.opengl.GLAutoDrawableBase$2.run(GLAutoDrawableBase.java:443)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1293)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
	at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:782)
	at com.jogamp.opengl.util.AWTAnimatorImpl.display(AWTAnimatorImpl.java:81)
	at com.jogamp.opengl.util.AnimatorBase.display(AnimatorBase.java:453)
	at com.jogamp.opengl.util.FPSAnimator$MainTask.run(FPSAnimator.java:178)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
	at java.base/java.util.TimerThread.run(Timer.java:516)
RuntimeException: java.lang.NoSuchMethodError: 'void processing.core.PVector.add(processing.core.PVector)'
`

**Comment by PolarCoords** [comment]
you'll need to use processing 2 or 1 because objloader is outdated and hasn't been updated for processing 4
